sudo: false

stages:
  - integration
  - release

env:
  global:
    - CACHE_NAME=${TRAVIS_JOB_NAME}


_commands_provider:

  _test: &_test make test

  _lint: &_lint make lint

  _release: &_release make release

  _install_requirements: &_install_requirements make dep

  # https://ttcshelbyville.wordpress.com/2012/12/19/disable-remote-differential-compression-form-the-command-line/
  _disable_windows_compression: &_disable_windows_compression "powershell Disable-WindowsOptionalFeature -Online -FeatureName MSRDC-Infrastructure"

  # https://travis-ci.community/t/yarn-network-troubles/333/7
  _disable_windows_defender: &_disable_windows_defender "powershell Set-MpPreference -DisableRealtimeMonitoring \\$true"


_steps_provider:

  _test: &_step_test

    install:
      - *_install_requirements
    before_script: *_lint
    script: *_test

  _release: &_step_release

    install: *_install_requirements
    script: *_release



jobs:
  include:

    - stage: integration
      name: py27-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=2.7.14
      before_install: source setup-pyenv.sh
      <<: *_step_test
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py36-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      <<: *_step_test
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py37-macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.7.3
      before_install: source setup-pyenv.sh
      <<: *_step_test
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: integration
      name: py27-linux
      language: python
      python: "2.7"
      <<: *_step_test

    - stage: integration
      name: py36-linux
      language: python
      python: "3.6"
      <<: *_step_test

    - stage: integration
      name: py37-linux
      language: python
      dist: xenial
      python: "3.7"
      <<: *_step_test

    - stage: release
      name: macos
      os: osx
      language: generic
      osx_image: xcode7.3
      env:
        - PYENV_VERSION=3.6.4
      before_install: source setup-pyenv.sh
      <<: *_step_release
      cache:
        directories:
          - ${HOME}/.pyenv_cache

    - stage: release
      name: linux
      language: python
      python: "3.6"
      <<: *_step_release

    - stage: release
      name: windows
      os: windows
      language: shell
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
        - *_disable_windows_compression
        - *_disable_windows_defender
        - choco install make
        - choco install python --version 3.7.3
      <<: *_step_release
